name: userhub
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  dartz: ^0.10.0
  flutter_riverpod: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.9.5
  retrofit: ^4.0.1
  retrofit_generator: ^9.1.9
  freezed: ^3.0.6


flutter:

  uses-material-design: true
